# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

#    - name: Get Go cache directories
#      id: go-cache-paths # ID para este paso
#      run: |
#        echo "GOMODCACHE_PATH=$(go env GOMODCACHE)" >> $GITHUB_OUTPUT
#        echo "GOCACHE_PATH=$(go env GOCACHE)" >> $GITHUB_OUTPUT
#        echo "GOVERSION=$(go env GOVERSION)" >> $GITHUB_OUTPUT
#        echo "GOPATH=$(go env GOPATH)" >> $GITHUB_OUTPUT

#    - name: Cache Go restore
#      uses: actions/cache/restore@v4
#      id: go-cache-restore
#      with:
#        path: |
#          ${{ steps.go-cache-paths.outputs.GOMODCACHE_PATH }}
#          ${{ steps.go-cache-paths.outputs.GOCACHE_PATH }}
#          ${{ env.GITHUB_WORKSPACE }}/.datadog
#          ${{ steps.go-cache-paths.outputs.GOPATH }}/bin/orchestrion
#        key: ${{ runner.os }}-go-test-optimization-v3-${{ steps.go-cache-paths.outputs.GOVERSION }}-${{ hashFiles('**/go.mod') }}-${{ hashFiles('**/go.sum') }}

    - name: Configure Datadog Test Optimization
      uses: datadog/test-visibility-github-action@v2
      with:
        languages: go
        api_key: ${{secrets.DD_API_KEY}}

    - name: Run
      run: |
        du $(go env GOMODCACHE) -h -s
        go run ./...

#    - name: Cache Go save
#      uses: actions/cache/save@v4
#      if: steps.go-cache-restore.outputs.cache-hit != 'true'
#      with:
#        path: |
#          ${{ steps.go-cache-paths.outputs.GOMODCACHE_PATH }}
#          ${{ steps.go-cache-paths.outputs.GOCACHE_PATH }}
#          ${{ env.GITHUB_WORKSPACE }}/.datadog
#          ${{ steps.go-cache-paths.outputs.GOPATH }}/bin/orchestrion
#        key: ${{ steps.go-cache-restore.outputs.cache-primary-key }}

